import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import ManWithDumbells from "../assets/pexels-mister-mister-3490348.jpg"
import { SiTwitter, SiFacebook, SiInstagram } from 'react-icons/si'

export default function LandingScreen() {
    return (
      <>
        <Head>
          <title>T.W.D.</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className='pt-20'>
          <div className="flex justify-center content-center items-center">
            <div className="flex flex-col gap-10 my-auto -z-10">
                <div><h1 className="font-AbrilFatface text-4xl translate-x-44 translate-y-28">TrainWithDean</h1></div>

                <div className="flex flex-col gap-3 py-10 pl-5 pr-16 bg-grey max-w-xl rounded-lg translate-x-16 translate-y-28">
                    <h2 className="font-AbrilFatface text-2xl">Dedicate yourself to becoming the best version of yourself.</h2>
                    <p className="text-lg">
                    At TWD our goal is to focus on your goals, whilst creating a pathway and structure that's easy to follow. Allowing you to create the best version of yourself.
                    </p>
                </div>
            </div>
            <div><Image className="rounded-lg" src={ManWithDumbells} alt={"Man With Dumbells"} width={324}/></div>
          </div>
          <div className="flex flex-col gap-4 content-center items-center pb-2 pt-28">
            <Link className='bg-charcoal text-white text-lg font-bold py-1 px-5 rounded-lg' href={""}>Enquire Now</Link>
            <div className="flex gap-6">
                {/* Twitter */}
                <div className='hover:animate-bounce'>
                    <a href="" target="_blank" rel="noreferrer">
                        <SiTwitter color='#39393A' fontSize={20}/>
                    </a>
                </div>
                {/* Facebook */}
                <div className='hover:animate-bounce'>
                    <a href="" target="_blank" rel="noreferrer">
                        <SiFacebook color='#39393A' fontSize={20}/>
                    </a>
                </div>
                {/* Instagram */}
                <div className='hover:animate-bounce'>
                    <a href="" target="_blank" rel="noreferrer">
                        <SiInstagram color='#39393A' fontSize={20}/>
                    </a>
                </div>
            </div>
          </div>
        </main>
      </>
    )
  }