import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import ManWithDumbells from "../assets/pexels-mister-mister-3490348.jpg"
import { SiTwitter, SiFacebook, SiInstagram } from 'react-icons/si'

export default function LandingScreen() {
    return (
      <>
        <Head>
          <title>T.W.D.</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className='pt-20 pb-6'>
          <div className="flex justify-center content-center items-center">
            <div className="flex flex-col gap-10 my-auto -z-10">
                <div><h1 className="font-AbrilFatface text-4xl translate-x-36 md:translate-x-64 lg:translate-x-44 lg:translate-y-28">TrainWithDean</h1></div>

                <div className="flex flex-col gap-3 py-10 pl-5 lg:pr-16 bg-grey w-96 md:w-auto max-w-xl rounded-lg translate-x-24 lg:translate-x-16 lg:translate-y-28">
                    <h2 className="font-AbrilFatface text-lg md:text-2xl">Dedicate yourself to becoming the best version of yourself.</h2>
                    <p className="text-sm md:text-base lg:text-lg pr-56 lg:pr-0">
                    At TWD our goal is to focus on your goals, whilst creating a pathway and structure that&apos;s easy to follow. Allowing you to create the best version of yourself.
                    </p>
                </div>
            </div>
            <div><Image className="rounded-lg drop-md mt-20 max-w-[200px] lg:max-w-[300px] max-h-[600px] -translate-x-28 translate-y-32 lg:translate-x-0 lg:translate-y-0" src={ManWithDumbells} alt={"Man With Dumbells"} width={4000} height={6000}/></div>
          </div>
          <div className="flex flex-col gap-8 content-center items-center pb-2 pt-44 lg:pt-28">
            <Link className='bg-charcoal text-white text-lg font-bold py-1 px-5 rounded-lg' href="#cta">Enquire Now</Link>
            <div className="flex gap-6">
                {/* Twitter */}
                <div className='hover:animate-bounce'>
                    <a href="" target="_blank" rel="noreferrer">
                        <SiTwitter color='#39393A' fontSize={20}/>
                    </a>
                </div>
                {/* Facebook */}
                <div className='hover:animate-bounce'>
                    <a href="https://www.facebook.com/profile.php?id=100083341510975" target="_blank" rel="noreferrer">
                        <SiFacebook color='#39393A' fontSize={20}/>
                    </a>
                </div>
                {/* Instagram */}
                <div className='hover:animate-bounce'>
                    <a href="https://www.instagram.com/train_with_dean/" target="_blank" rel="noreferrer">
                        <SiInstagram color='#39393A' fontSize={20}/>
                    </a>
                </div>
            </div>
          </div>
        </main>
      </>
    )
  }