import Head from 'next/head'
import { Inter } from '@next/font/google'
import NavBar from '@/components/NavBar'
import LandingScreen from '@/components/LandingScreen'
import Services from '@/components/Services'
import CTA from '@/components/CTA'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>T.W.D.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='font-PTSans scroll-smooth overflow-hidden'>

        <div>

          <div className="fixed w-full z-50">
            <NavBar/>
          </div>

          <div id="landing" className="pt-16 md:pt-8 lg:pt-4">
            <LandingScreen/>
          </div>

          <div id="services">
            <Services/>
          </div>

          <div id="cta">
            <CTA/>
          </div>

          <div>
            <Footer />
          </div>

        </div>

      </main>
    </>
  )
}
